### ISSUE TITLE
Error in app/styles/utilities/_lists.scss

### ISSUE THREAD

**Issue by aburd** [josephdburdick/front-end-flow#2]
After following steps in readme.md, I get:
```
Error in plugin 'sass'
Message:
    app/styles/utilities/_lists.scss
Error: Undefined variable: "$grid-gutter-width".
        on line 8 of app/styles/utilities/_lists.scss
>>   margin-left: -($grid-gutter-width / 8);
   -----------------^

[23:32:45] gulp-notify: [Error running Gulp] Error: app/styles/utilities/_lists.scss
Error: Undefined variable: "$grid-gutter-width".
        on line 8 of app/styles/utilities/_lists.scss
>>   margin-left: -($grid-gutter-width / 8);
   -----------------^
```

I think this particular variable is named **$grid-gutter-width-base** in app/styles/utilities/_variables.scss.

**Comment by josephdburdick** [comment]
Hey @aburd sorry I missed this issue but it looks like I already [patched it here](https://github.com/josephdburdick/front-end-flow/commit/0b0292071a33a441c2be7a0ee99d4bb57a014a94#diff-f4be8a52ccb51d56a4d0b848c6211ce0).
